### ISSUE TITLE
Rspec 3.1: uninitialized constant RSpec::Support

### ISSUE THREAD

**Issue by dvrensk** [rubyworks/rspec-ontap#1] opened 2015-01-02 14:41 UTC
I tried running rspec-ontap with Rspec 3.1 and Rails 4.2, but got this error:

```
.../gems/rspec-core-3.1.7/lib/rspec/core/formatters/base_formatter.rb:1:in `<top (required)>': uninitialized constant RSpec::Support (NameError)
from .../gems/rspec-ontap-0.2.0/lib/rspec/ontap.rb:1:in `require'
from .../gems/rspec-ontap-0.2.0/lib/rspec/ontap.rb:1:in `<top (required)>'
from ...@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:85:in `require'
from ...@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:85:in `rescue in block in require'
from ...@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:68:in `block in require'
from ...@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:61:in `each'
from ...@global/gems/bundler-1.7.8/lib/bundler/runtime.rb:61:in `require'
from ...@global/gems/bundler-1.7.8/lib/bundler.rb:134:in `require'
from myapp/config/application.rb:15:in `<top (required)>'
from .../gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
from .../gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
from .../gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
from .../gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
from .../gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
from .../gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
from .../gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
from .rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from .rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from -e:1:in `<main>'
```

Is this gem still being maintained?

**Comment by trans** [comment] 2015-01-02 14:59
Yes --though lower priority since I do less Ruby coding these days. If you have a fix I will gladly merge. Otherwise I will take a look as soon as I can.

**Comment by dvrensk** [comment] 2015-01-02 19:38
Thanks for your quick response!  I had never heard about Tap before today, and I just wanted to test it.  If I were a real user I would look into fixing it, but right now I can't prioritise it.

Thanks for your work!

**Comment by trans** [comment] 2015-01-17 16:05
Should all be fixed now. There were a lot of API changes in v3+!

(Btw, not sure the error you got was actually caused by rspec-ontap. Notice the error was in the base_formatter.rb file of rspec itself. But even if so it has been fixed b/c things are running smooth on my end now with all the latest installs.)

BIG THANKS!!!!

**Closed as completed by trans** 2015-01-17 16:05 UTC
